### ISSUE TITLE
Client.InvalidParameterCombination

### ISSUE THREAD

**Issue by akumria** [AutoSpotting/AutoSpotting#346] opened 2019-06-05 13:40 UTC
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```
Autospotting-7c880e2b-LambdaFunction-H3A3TP056E3Z
```

## Configuration ##

Unknown to me, being run by the organisations Cloud team

## Environment ##

- AWS region: us-west-2 but also seen in other regions
- Type of environment: VPC
- Anonymized launch configuration: 

```text
```

## Summary ##

AutoSpotting fails to launch as it miscombines parameters, from AWS:

```
"errorCode": "Client.InvalidParameterCombination",
    "errorMessage": "The parameter 'iamInstanceProfile.name' may not be used in combination with 'iamInstanceProfile.arn'",
```

## Steps to reproduce ##

Launch auto-scale group, enable autospotting, 

## Expected results ##

* An instance to be correctly launched.

## Actual results ##

* Many (many!) failed calls to the AWS API
* AWS API Limits exceeded

Please see the error message above.

**Comment by cristim** [comment] 2019-06-05 14:55
Thanks for reporting this issue, are you by any chance using Launch Templates? This feature is relatively new and still experimental, it just landed a few days ago and someone already revealed some issues 

I suspect that one of either the Name or the ARN come from the launch template, and the other from the launch configuration.

As a potential fix we could check if both of them are set when we prepare the data for the RunInstances API call and set the name one to nil.

The same approach could be used to address the other issue, #345

Feel free to create a PR with a fix, should be relatively easy.

**Comment by akumria** [comment] 2019-06-05 15:20
Yes we are using LaunchTemplates.

Unfortunately the team responsible for deploying AutoSpotting were unaware that Launch Template support is very new; that may be worth highlighting more broadly.

I did, briefly, consider contributing however the differing licences between source and binary make this a non-starter for me.

**Comment by cristim** [comment] 2019-06-05 17:59
Okay, please bear with me with the LaunchTemplate support, I hope we'll sort out these kinks soon.

Regarding the license, the source code is licensed under the MIT license. This means that anyone can have closed source forks and/or release closed source binaries based on this MIT code.

I know of a startup who built their entire product based on this code and another who enhanced their existing product based on code from this repo. Neither of these contributed anything back. That's not so nice of them but the license allows it. If you have a problem with that and you don't want to contribute because of the license, it's up to you to decide.

The binaries I build are built directly from this open source code, there's nothing more to it. You're free not to use them if their license bothers you, just build from source yourself and run it from your own binaries.

I'm just trying to extract a little income from people who aren't willing to spend time compiling it from source code and would rather get it from my S3 bucket and/or would be willing to pay for telling them which of the trunk builds I had tested and deemed to be stable so they don't have to test it themselves.

It's nothing spectacular, currently just enough to pay for my personal AWS account hosting this S3 bucket and to cover my digital subscriptions(Kindle, Audible, Spotify, Medium, Blinkist, etc.) in order to keep me motivated to continue working on this project in my spare time and justify to my wife that I keep working on this after all this time.

**Comment by cristim** [comment] 2019-06-27 15:33
Maybe sightly related to this, I've just implemented support for skipping ASGs with mixed instances(the AWS native on-demand+spot support for ASGs), previously we were attempting to replace their on-demand instances and likely entering race conditions.

I'm now ready to help with this LaunchTemplate issue but need some information on how to reproduce this problem.

**Closed** 2019-06-28 08:43 UTC
Labels: Status: Help wanted, Type: Bug

**Comment by cristim** [comment] 2019-06-28 08:44
This should be fixed in the latest version, please give it a try and let me know if you still notice any issues.
