### ISSUE TITLE
Pause autospotting when instance type is oversubscribed

### ISSUE THREAD

**Issue by croman** [AutoSpotting/AutoSpotting#293] opened 2018-09-04 16:32 UTC
When there's a high demand for a particular type of instance, the spot instances start getting the termination notification and shut down. Autospotting then replaces the newly created normal instances with spot, but those soon get terminated as well, and the cycle continues.

This happened to me twice, with different instance types (m3.medium and t2.small) but each time with only one type of instance dying and this process going on for hours. I have noticed that when this issue occurs the time to fulfill a spot request is also higher.

In this case I would like for autospotting to detect a problem and pause replacing the instances temporary / permanent until manual restarting. Replacing too often can cause instability / performance issues in systems that require data migration between instances.

What do you think it's the best case to deal with this scenario?

**Comment by cristim** [comment] 2018-09-05 20:14
Thanks for reporting this issue, I definitely think this is valuable to have, I'm just not sure how should we implement it.

So far autospotting is only aware of the currently running instances, we do not consider the previous state, nor keep track of the instances that were launched or terminated recently in order to determine the stability level of the instance types.

We would need to store a sort of log of the spot instances and avoid those that have been terminated by the market within the last few hours. I think the best place for this would be a DynamoDB table, but we would need to provision and make use of it, since we don't have any persistence yet.

To answer your second question, Autospotting currently only attempts to launch the cheapest instance type in the given availability zone. If this fails due to insufficient spot capacity we just skip the current run and try again in the subsequent runs, likely with the same instance type. We don't try to launch other instance types if the cheapest failed to launch. We have a feature request for this but it wasn't implemented yet.

I don't have much bandwidth to do these things anytime soon, but if you are interested in contributing either or even better both these features, I would gladly consider some PRs.

**Comment by cristim** [comment] 2019-04-28 13:34
We recently started to iterate over the compatible instance types and attempt to launch each of them until we succeed launching one.

I think this should mitigate this issue, so I propose we close this issue. 

But please reopen it if you can still reproduce it with a more recent build.

**Closed by cristim** 2019-04-28 13:34 UTC

**Comment by lenucksi** [comment] 2019-04-28 14:33
> We recently started to iterate over the compatible instance types and attempt to launch each of them until we succeed launching one.
Details should be available in #306 and #263 I think.
