### ISSUE TITLE
spot instances dont run respective autoscaling group launch configuration

### ISSUE THREAD

**Issue by sbonasu** [AutoSpotting/AutoSpotting#438] opened 2020-10-08 20:06 UTC
# Github issue #

Respect auto scaling group launch configuration

## Issue type ##

- Bug Report

## Build number #

commit af0fec8119acf4e4f19574dca8b25b4621f35e7e
Implement event-based instance replacement

## Summary ##

We do configuration management on EC2 via Userdata scripts when they are being launched rather than using pre built AMI. When spot instances are launched, they don't respect auto scaling group launch configuration.

## Expected results ##

Run respective asg launch configuration userdata script on spot instances

**Comment by cristim** [comment] 2020-10-08 21:42
Thanks for reporting this issue.

Could you please explain in more detail what's happening, what Userdata do the instances get?

it would be great if you could share the anonymized logs of a run of the Lambda function that shows this behavior.

**Comment by sbonasu** [comment] 2020-10-09 14:17
we get the latest amazon linux 2 AMI using ssm parameter in cloudformation template then use launch configuration userdata script to do configuration management of ASG instances.

AmiId:
    Description: ec2-Optimized AMI ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

When on-demand instances are replaced with spot, spot instances launch with vanilla Amazon linux 2 AMI without any configuration we do via launch configuration

you can recreate this issue by creating asg instances with userdata(create a sample file in ec2) in launch configuration then let your lambda replace them with spot. spot instances wont have that sample file you are creating via userdata

**Comment by cristim** [comment] 2020-10-09 14:45
Can you share some infrastructure code you used, in order to be able to easier reproduce this ?

**Comment by sbonasu** [comment] 2020-10-14 13:48
you can use this template

https://github.com/aws-samples/ecs-refarch-cloudformation/blob/master/infrastructure/ecs-cluster.yaml

**Comment by cristim** [comment] 2020-10-14 14:51
thanks, I'll have a look soon

**Comment by cristim** [comment] 2020-10-15 00:06
I had a look and found a number of bugs in the current implementation.

I pushed a few fixes but it's not ready yet, stay tuned for more changes over the next few days.

**Comment by cristim** [comment] 2020-10-16 09:23
I'm closing this as I can't reproduce it with the latest build, please reopen if you still notice this issue.

**Closed by cristim** 2020-10-16 09:23 UTC
