### ISSUE TITLE
Beanstalk initialization issue after CloudFormation update on 5/30/2019

### ISSUE THREAD

**Issue by jawadst** [AutoSpotting/AutoSpotting#344] opened 2019-06-04 13:42 UTC
## Issue type ##

- Bug Report

## Build number #

build nightly-1038

## Environment ##

eu-central-1c with Beanstalk / ECS / EC2

## Summary ##

Autospotting used to work perfectly with Beanstalk and I was a happy man.
The Beanstalk setup is the following: it uses CloudFormation to create an auto-scaling group. When an EC2 instance is launched by the auto-scaling group, it uses `cfn-init` (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-init.html) to configure itself as part of its UserData script (https://s3.dualstack.eu-central-1.amazonaws.com/elasticbeanstalk-env-resources-eu-central-1/stalks/eb_docker_ecs_4.2.1.200714.0/lib/UserDataScript.sh).
AutoSpotting applied to the auto-scaling group created by Beanstalk/CloudFormation used to work perfectly.

On 5/30/2019, AWS CloudFormation changed the way it authorizes requests from `cfn-init` and now requires the instance calling it to be a part of the CloudFormation stack it is trying to reference. This means that the instance has to have a `aws:cloudformation:stack-id` tag and that CloudFormation only allows calls from instances tagged that way (that is known as the `CFN signer` and is a special, internal-only, undocumented feature of CloudFormation for authorizing API requests coming from EC2 instances: see https://serverfault.com/questions/638096/how-is-cloudformation-metadata-access-controlled/787234 and https://stackoverflow.com/questions/29393675/does-aws-cfn-init-need-a-profile-role-for-describestackresource/38112522). CloudFormation also allows the regular instance-based credentials calls (with the `--role` option passed to `cfn-init`) but that is not how Beanstalk uses `cfn-init` so adding the correct permission to the instance role does not help.

The issue is that, when it gets launched by AutoSpotting, a spot instance does not have the `aws:cloudformation:stack-id` tag and is not a part of the CloudFormation stack. The tag cannot be added to an instance by AutoSpotting itself as tags starting with `aws:` are restricted to AWS services. The tag gets added once the instance gets attached to the auto-scaling group but it is too late for `cfn-init` to run properly.
`cfn-init` retries for up to 5 minutes though so once the instance gets attached to the auto-scaling group (and assuming it takes less than 5 minutes for the instance to be attached), the initialization process can continue normally. In my experience, it sometimes works and sometimes doesn't and adds some unwelcome randomness to the process.

After discussing with AWS support, a potential fix would be to slightly alter the UserData to force the inclusion of a role with a script like this (prepend this to the UserData copied from the auto-scaling group):
```
---- modify cfn-init and cfn-get-metadata ----
# Modify cfn-init and cfn-get-metadata to use --role by default
echo -e '#!/bin/bash -x \nINROLE=`curl 169.254.169.254/latest/meta-data/iam/security-credentials/`\n/opt/aws/bin/cfn-init-2 --role $INROLE "$@" \nexit $?' > /opt/aws/bin/cfn-init.tmp
mv /opt/aws/bin/cfn-init /opt/aws/bin/cfn-init-2
mv /opt/aws/bin/cfn-init.tmp /opt/aws/bin/cfn-init
chmod +x /opt/aws/bin/cfn-init
---- modify cfn-init and cfn-get-metadata ----
```

This is pretty hacky but is a somewhat working solution.

I was curious to see if you had any idea on how to alter UserData via AutoSpotting or a better solution.

## Steps to reproduce ##

- Launch a Beanstalk environment with an ELB/auto-scaling enabled
- Run auto-spotting on the auto-scaling group created
- Check system logs of spot instances launched by AutoSpotting

## Expected results ##

`cfn-init` completes without errors

## Actual results ##

`cfn-init` logs an error:
```
[eb-cfn-init]: [2019-06-01T14:46:18.319Z] Tailing /var/log/cfn-init.log
[eb-cfn-init]: 
[eb-cfn-init]: ******************* cfn-init taillog *******************
[eb-cfn-init]:     raise exc[0]
[eb-cfn-init]: HTTPError: 400 Client Error: Bad Request
[eb-cfn-init]: 2019-06-01 14:45:29,505 [ERROR] Throttling: Rate exceeded
[eb-cfn-init]: Traceback (most recent call last):
[eb-cfn-init]:   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
[eb-cfn-init]:     return f(*args, **kwargs)
[eb-cfn-init]:   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
[eb-cfn-init]:     raise exc[0]
[eb-cfn-init]: HTTPError: 400 Client Error: Bad Request
[eb-cfn-init]: 2019-06-01 14:45:38,369 [ERROR] Throttling: Rate exceeded
[eb-cfn-init]: Traceback (most recent call last):
[eb-cfn-init]:   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
[eb-cfn-init]:     return f(*args, **kwargs)
[eb-cfn-init]:   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
[eb-cfn-init]:     raise exc[0]
[eb-cfn-init]: HTTPError: 400 Client Error: Bad Request
```

**Comment by cristim** [comment] 2019-06-04 15:09
Thanks for reporting this issue, having Beanstalk support a very critical feature, and I have a few ideas for how to tackle it without patching the userdata:

- intercept any instance launches for the groups maintained by Autospotting, immediately launch a spot replacement and swap it against the fresh on demand instance, which is then terminated. This way the spot instance would be part of the group by the time we run the cfn-init script.
- implement a mode of running in which we would use the mixed groups Autoscaling feature, by updating the launch configuration of the group. This way the groups are entirely managed by Autoscaling, we just offer a nicer way to configure it based on tags and autodetection of the compatible instance types.

Unfortunately I don't have much time to work on this these days but if you are interested feel free to pick up either of these proposals and submit a pull request.

**Comment by jawadst** [comment] 2019-06-04 15:55
Good ideas and thanks for spending some time on this.

#1 seems to have the drawback that if, for any reason, the spot instance fails, the on-demand won't be there anymore. I think a great strength of autospotting is that you only remove the on-demand once the spot has been fully validated and is in service. It provides for a very solid fallback to on-demand instances when things go south and feels very safe as a company using it.
I'll do some research on #2 that seems pretty interesting, I did see that auto-scaling now had a mixed group feature.

**Comment by tbutkiewicz** [comment] 2019-06-11 04:27
You can sidestep mucking with adding the role to the cfn script by updating the instance profile/role assigned to your EC2 instances.  Either way, you are granting access from the instance to the stack.

Although not _truly_ least privileged, adding something like this will match Beanstalk CF stacks so AutoSpotting can still do its thing:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowCloudformationOperationsOnElasticBeanstalkStacks",
            "Effect": "Allow",
            "Action": [
                "cloudformation:*"
            ],
            "Resource": [
                "arn:aws:cloudformation:*:*:stack/awseb-*",
                "arn:aws:cloudformation:*:*:stack/eb-*"
            ]
        }
    ]
}
```
You can further restrict it as necessary - Hope that helps!

**Comment by jawadst** [comment] 2019-06-11 14:28
@tbutkiewicz 
Thanks for the idea. Unfortunately, the `cfn-init` script specifically does not rely on the instance profile/role and uses a special authentication method that is specific to CloudFormation and authenticates the instance from its tags.
The way to tell the `cfn-init` script to use the instance role is by modifying the way it's called which is the tricky part with Beanstalk.

**Comment by JerimyTate** [comment] 2019-06-11 16:06
@jawadst are you just updating the userdata manually or did you make changes to autospotting to make these changes on your behalf?

**Comment by jawadst** [comment] 2019-06-11 17:59
@JerimyTate I haven't had a chance to try out any solution yet :)
I guess forking/updating AutoSpotting would be the easiest option to patch the UserData on the fly when there is a cfn-init script involved.

**Comment by JerimyTate** [comment] 2019-06-11 18:24
Yeah we were hoping to give this a test run, but until I figure out how to patch in UserData not going to work for us unfortunately. I've tried to look through the code, but not seeing where the existing UserData is set. @cristim any help to get us pointed in the right direction?

**Comment by tbutkiewicz** [comment] 2019-06-11 18:31
> @tbutkiewicz
> Thanks for the idea. Unfortunately, the `cfn-init` script specifically does not rely on the instance profile/role and uses a special authentication method that is specific to CloudFormation and authenticates the instance from its tags.
> The way to tell the `cfn-init` script to use the instance role is by modifying the way it's called which is the tricky part with Beanstalk.

The update to IAM permissions does work, and has been working with success since 5/30 with Beanstalk baked cfn-init scripts from Beanstalk AMIs/SolutionStacks.  cfn-init will inherit permissions granted by instance role just like other scripts on the EC2 instance.  Although cfn-init documentation does specify how to manually use a IAM role when running the script, this approach works as well.

It is easy to test out, you may find it as an easy solution :)

**Comment by cristim** [comment] 2019-06-11 19:04
Have a look around line 553 in https://github.com/AutoSpotting/AutoSpotting/blob/master/core/instance.go

**Comment by cristim** [comment] 2019-06-12 20:18
Do you guys need any help with this? Patching the userdata script in a quick and dirty fork should be pretty straightforward, I can help if you are struggling with this.

The most challenging part is addressing this properly in a way that can be merged into the upstream repo.

**Comment by JerimyTate** [comment] 2019-06-14 15:43
@tbutkiewicz so was able to recreate your fix and it does work! I think you actually need to only add 
```
            - cloudformation:SignalResource
            - cloudformation:DescribeStackResource
```
so adding something this below would be more in line with least privilege 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowCloudformationOperationsOnElasticBeanstalkStacks",
            "Effect": "Allow",
            "Action": [
            "cloudformation:SignalResource",
            "cloudformation:DescribeStackResource"
            ],
            "Resource": [
                "arn:aws:cloudformation:*:*:stack/awseb-*",
                "arn:aws:cloudformation:*:*:stack/eb-*"
            ]
        }
    ]
}```

**Comment by cristim** [comment] 2019-06-14 18:10
Thanks guys, please create a PR with a documentation fix.

I guess it would also be possible to automatically inject this statement into the IAM instance profile attached to instances belonging to these Beanstalk Cloudformation stacks.

Would you find this valuable?

**Comment by jawadst** [comment] 2019-06-14 18:17
@JerimyTate 
How did you validate that it worked? Do you not see a 400 error in the system logs anymore?
I have tried that solution and have not been able to make it work so maybe I did something wrong.

**Comment by JerimyTate** [comment] 2019-06-14 18:46
@jawadst We added following IAM permissions to our existing beanstalk role
```        {
            "Sid": "AllowCloudformationOperationsOnElasticBeanstalkStacks",
            "Effect": "Allow",
            "Action": [
            "cloudformation:SignalResource",
            "cloudformation:DescribeStackResource"
            ],
            "Resource": "*"
        }```

From this we were able to successfully get autospotting to bootstrap a spot beanstalk instance,  place it into the ASG, and an existing instance was terminated. We made no changes to userdata scripts.

**Comment by jawadst** [comment] 2019-06-14 19:03
@JerimyTate 
Thanks for the info. To be clear, the issue does not prevent AutoSpotting from working, it makes the setup of the instance slower and sometimes fails randomly but it still works most of the time.  
The reason is that once AutoSpotting attaches the spot instance to the autoscaling group then `cfn-init` works correctly and the instance continues its setup process after that happens. The instance setup is blocked until it gets attached though.

Mind checking the system log of one of your spot instances to see if you have a "400 Client Error: Bad Request"? That's the main way to see if the issue is really fixed or not.

**Comment by JerimyTate** [comment] 2019-06-14 19:59
@jawadst so I could confirm you are correct we are still seeing these errors on bootstrap, but I have yet to see the intermittent failures, but it does look like a userdata solution will be required

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:20:53,101 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:20:53,884 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:20:56,901 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:21:05,973 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:21:06,330 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:21:19,759 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:21:27,495 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:21:41,232 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:21:59,037 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:22:03,983 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:22:20,917 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:22:26,309 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:22:35,330 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:22:48,991 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:23:07,205 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:23:20,978 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:23:32,944 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:23:41,105 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:23:52,697 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:23:53,494 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:23:55,519 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:24:10,973 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:24:14,493 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:24:20,579 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:24:29,155 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:24:48,658 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:25:07,465 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
HTTPError: 400 Client Error: Bad Request
2019-06-14 14:25:22,460 [ERROR] Throttling: Rate exceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
```

**Comment by cristim** [comment] 2019-07-25 16:07
For anyone brave enough to be a guinea pig for barely tested code, the latest build from the #354 branch may mitigate this issue.

To install is just click on this URL:
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/template?stackName=AutoSpotting&templateURL=https://s3.amazonaws.com/cloudprowess/custom/template_build_1439509.yaml

**Comment by towczare** [comment] 2019-07-27 17:47
Cristian, thanks a lot for an update. 
I played with this version just a little bit and discovered strange behavior during scaling up instances. 
![spot](https://user-images.githubusercontent.com/11510145/61997773-192e4300-b0a7-11e9-8cac-33e17ab47fe7.png)
It looks like the spot instances were being spawned but then instantly killed instead of replacement of two normal instances left (as you can see there is quite of them) 
I will try to take a look more closely tommorow. 


PS. Had to change one of the parameters in your mentioned stack to make it work **LambdaS3BucketPrefix** default option `nightly` needs to be changed to `custom` 
Might be hint for others testing this out.

**Comment by cristim** [comment] 2019-07-29 10:02
@towczare thanks for testing and reporting this.

My tests so far have been just by running AutoSPotting locally against custom JSON events. I didn't actually run it end to end as it runs from lambda yet due to lack of time.

This looks like a bug in the event handling, I'll look into this and also run it from Lambda myself.

**Comment by cristim** [comment] 2019-07-29 13:56
I also got it tested on my side and for single-instance replacements this seems to work quite reliably but it turns out there's a race condition with the AutoScaling group when multiple on-demand instances are launched and replaced at the same time, like it is the case for a new group or when scaling out by multiple nodes simultaneously.

For a short time, after we launch and attach spot instances but before we detach and terminate on-demand ones,  the group increases in capacity beyond the DesiredCapacity and AutoScaling terminates some instances in order to bring the group back to the desired capacity.

It happened that freshly launched spot instances were terminated by the ASG so that group was then left with on-demand instances.

I think that setting the Lambda concurrency to 1 may help with this.

**Comment by cristim** [comment] 2019-07-31 19:46
@towczare please try https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/template?stackName=AutoSpotting&templateURL=https://s3.amazonaws.com/cloudprowess/custom/template_build_94d2077.yaml (requires the same parameter change you mentioned).

At least in my case it seemed to work fine on a group of 4 instances.

**Comment by towczare** [comment] 2019-08-01 08:48
Thanks for your fast contribution @cristim Unfortunately I don't know golang, so I will at least help a little bit as tester :slightly_smiling_face:  I ran a couple of tests today, playing with it a bit. 
Here are my observations:

1) First test I run up, was some agresive scaling (+2 to existing 2) and race condition was also noticable.
![Screenshot from 2019-08-01 10-37-40](https://user-images.githubusercontent.com/11510145/62278566-a3303000-b448-11e9-9162-113a39842cb7.png)
![Screenshot from 2019-08-01 10-37-49](https://user-images.githubusercontent.com/11510145/62278579-a88d7a80-b448-11e9-8daf-c9e769992bb6.png)
![Screenshot from 2019-08-01 10-37-59](https://user-images.githubusercontent.com/11510145/62278588-ab886b00-b448-11e9-94cf-70a5202cdd49.png)
![Screenshot from 2019-08-01 10-38-08](https://user-images.githubusercontent.com/11510145/62278591-af1bf200-b448-11e9-9c94-3014a20f9608.png)
then I decided to go for a breakfast and leave it, to see if this is sort of infinite loop or some random replacement. This is how it looks like after my come back
![Screenshot from 2019-08-01 10-38-15](https://user-images.githubusercontent.com/11510145/62278638-c5c24900-b448-11e9-91dd-ba67aaa56f39.png)

I decided to simplify it and check if soft scaling is also affected. 

2) During soft scale up test (+1 instance to 2 existing instances) everything went fine as expected
![Screenshot from 2019-08-01 10-21-49](https://user-images.githubusercontent.com/11510145/62277973-85160000-b447-11e9-85a4-930f68b10eb8.png)
![Screenshot from 2019-08-01 10-22-06](https://user-images.githubusercontent.com/11510145/62278009-9232ef00-b447-11e9-9db6-85bcb7bc2823.png)
![Screenshot from 2019-08-01 10-32-42](https://user-images.githubusercontent.com/11510145/62278113-b7276200-b447-11e9-8402-c147eb5e1cc7.png)

So far so good. Let's try it another time.

3)  Then during another scale up (+1 to 3 existing instances) race condition started.
![Screenshot from 2019-08-01 10-22-34](https://user-images.githubusercontent.com/11510145/62278232-f35ac280-b447-11e9-9a26-81c34e9422f5.png)
![Screenshot from 2019-08-01 10-22-43](https://user-images.githubusercontent.com/11510145/62278246-f8b80d00-b447-11e9-8d80-aa557a639a17.png)
![Screenshot from 2019-08-01 10-22-57](https://user-images.githubusercontent.com/11510145/62278248-fa81d080-b447-11e9-944a-f7178303dcfa.png)
![Screenshot from 2019-08-01 10-23-19](https://user-images.githubusercontent.com/11510145/62278261-ff468480-b447-11e9-99a7-4aaca9322d0d.png)
![Screenshot from 2019-08-01 10-44-40](https://user-images.githubusercontent.com/11510145/62278958-6b75b800-b449-11e9-923d-0a102b7efb2a.png)

as I already know it might end as expected I manually killed normal isntance.

**Comment by cristim** [comment] 2019-08-01 09:30
@towczare I'm very surprised about these results. Are you sure you run the latest version?

**Comment by towczare** [comment] 2019-08-01 09:43
@cristim I double-checked. This is the latest stack provided by you. Pointing to **lambda_build_94d2077.zip**

**Comment by towczare** [comment] 2019-08-01 10:20
I removed a different stack of autospotting, used a different tag for discovery and I am just running my tests again. The first scenario mentioned earlier (2 + 2 instances) seems to be reproduced.
![Screenshot_2019-08-01 Instances EC2 Management Console(26)](https://user-images.githubusercontent.com/11510145/62285807-aaf6d100-b456-11e9-8f5a-3248a6be9e19.png)

**Comment by cristim** [comment] 2019-08-02 10:40
I'm going to work on this race condition after I'm done with the lifecycle hooks work I'm currently doing.

The idea so far is to temporarily suspend the Termination process of the Autoscaling group for a few minutes. Since this isn't supported by the API I'm going to have to create a workaround using DynamoDB TTLs as described on gitter.im

**Comment by cristim** [comment] 2019-08-12 16:15
@towczare I implemented a naive but simple fix in the custom build 0783910, please give it a try.

Over the last few days I focused on lifecycle hook support and I didn't yet test it in groups with concurrent instance replacements, but it might work. I'm now suspending the termination lifecycle processes during an instance replacement. If this isn't working as expected I'll try to implement something using DynamoDB but I'd avoid that if possible since it would complicate the design a bit.

**Comment by towczare** [comment] 2019-08-14 13:29
Great news! Currently I am on vacation, so I will take a look into this next week.

**Comment by towczare** [comment] 2019-08-27 08:24
@cristim sorry it took so long but this is the earliest I could test build **0783910**
During upscaling one by one, two strange behaviors were noticed by me:
* First one was related with ordering too many spot instances and then terminating one of them (this is no big deal, actually I don't find it an as big problem at all)
![Screenshot_2019-08-27 Instances EC2 Management Console(1)](https://user-images.githubusercontent.com/11510145/63754133-a0dcbc80-c8b4-11e9-8de0-facc5a198dc7.png)
* Second one was noticed by me during upscaling from 3 to 5 instances. There were quite a lot of spot orders placed.
![Screenshot_2019-08-27 Instances EC2 Management Console(2)](https://user-images.githubusercontent.com/11510145/63754151-a803ca80-c8b4-11e9-8e05-5dd18406313a.png)
Note, for the above state, the expected number of instances were 5.

**Closed** 2019-10-11 20:31 UTC
Labels: Component: Core Logic, Difficulty: Hard, Importance: Major, Status: In progress, Status: Need testing, Status: outdated (to re-check), Type: Bug

**Comment by cristim** [comment] 2023-04-10 15:02
I'm going to remove this feature in the next version, as now we attach Spot instances to the ASG within seconds of them being launched.
